/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router at dev/build time.
// Do not edit this file manually.

import { createFileRoute, createRootRoute } from '@tanstack/react-router'

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'
import { Route as BuilderRoute } from './routes/builder'

const IndexRouteWithPath = IndexRoute.update({ path: '/' } as any)
const BuilderRouteWithPath = BuilderRoute.update({ path: '/builder' } as any)

export const routeTree = rootRoute.addChildren([
  IndexRouteWithPath,
  BuilderRouteWithPath,
])
